# Generated by Django 5.0 on 2023-12-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_prodcldsuct_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcldsuct',
            new_name='Product',
        ),
    ]
