# Generated by Django 5.0 on 2023-12-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategory_alter_product_slug_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='utlTitle',
            new_name='urlTitle',
        ),
    ]
