# Generated by Django 5.0 on 2023-12-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_utltitle_productcategory_urltitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='isDelete',
            new_name='is_Delete',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='urlTitle',
            new_name='url_Title',
        ),
    ]
