# Generated by Django 5.0 on 2023-12-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_isdelete_productcategory_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='is_Delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='url_Title',
            new_name='url_title',
        ),
    ]
