# Generated by Django 5.0 on 2023-12-22 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_is_delete_productcategory_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categoties', to='product.productcategory'),
        ),
    ]
