# Generated by Django 5.0 on 2024-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SieSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='دامنه سایت')),
                ('about_us_txt', models.TextField(verbose_name='درباره ما')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='ایمیل')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/setting', verbose_name='لوگو')),
                ('copyright', models.CharField(blank=True, max_length=50, null=True, verbose_name='کپی رایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
