# Generated by Django 5.0 on 2024-01-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SieSetting',
            new_name='SiteSetting',
        ),
    ]
