# Generated by Django 5.0 on 2024-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('url', models.URLField(max_length=255, verbose_name='لینک')),
                ('url_title', models.URLField(max_length=255, verbose_name='عنوان لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر',
                'verbose_name_plural': 'تصاویر اسلابدر',
            },
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': ' لینک فوتر', 'verbose_name_plural': ' لینک های فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footerlinkbox',
            options={'verbose_name': 'دسته بندی فوتر', 'verbose_name_plural': 'دسته بندی های فوتر'},
        ),
    ]
