# Generated by Django 5.0 on 2024-01-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_slider_is_active_alter_slider_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=400, verbose_name='url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='تصویر')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.CharField(choices=[('productList', 'صفحه لیست محصولات'), ('productDetail', 'صفحه جزئیات محصولات'), ('aboutus', 'درباره ما')], default='productList', max_length=200, verbose_name='محل نمایش')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
    ]
