# Generated by Django 5.0 on 2023-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('fullName', models.CharField(max_length=300, verbose_name='نام و نشان')),
                ('message', models.TextField(max_length=300, verbose_name='پیام')),
                ('isRead', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('responseText', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
